### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by 3noch** [comment]
@niklaswallerstedt Not sure if you're still interested in this project but I made some minor changes to your setup in this PR.

**Comment by niklaswallerstedt** [comment]
@3noch, I'm still interested for sure! :) I'll be happy to try it out tmrw, it does look a lot cleaner.

**Comment by 3noch** [comment]
@niklaswallerstedt Sweet. Your autoInstall feature is awesome. I will soon need to deploy a bunch of new wordpress sites and that will make it a lot easier. As a side note I'm pondering how to integrate plugin activation with that...

**Comment by niklaswallerstedt** [comment]
@3noch Seems to be working well from my initial testing!

**Comment by 3noch** [comment]
@niklaswallerstedt Awesome. Thanks for testing it.

**Pull request merged**
