### PR TITLE
Plugin activation

### LINKED ISSUE #15: Plugin activation
@3noch Regarding #14 and plugin activation. I would use [wp-cli for this as well](http://wp-cli.org/commands/plugin/activate/) and extend the install script. You could either pass a list of plugins to activate or activate them all with the `--all` option.

### PR DESCRIPTION
**Pull request by niklaswallerstedt**
@3noch Just something to get us going that fixes #15 . We do need to perform a check if there are any plugins that should be activated at all, as well as providing the actual list of plugins.

### CODE REVIEW

**Comment by 3noch** [comment]
Sweet! Thanks!

**Comment by 3noch** [comment]
@niklaswallerstedt I'll let you delete the branch if you're done with it.

**Comment by 3noch** [comment]
Oh haha maybe you meant for this PR to live a little longer. Sorry if that was the intent. I'll open a new PR soon to finish this.

**Comment by niklaswallerstedt** [comment]
@3noch hehe yeah, never mind :)

**Pull request merged**
